function P_error_k_1 = compute_error_cov(P_error_k, Q_expectation, R_expectation, KF, true_model, theta_specific_model)
    K_k_dash = true_model.Phi_k*KF.P_k*true_model.H_k' / ...
        (true_model.H_k*KF.P_k*true_model.H_k' + theta_specific_model.R);
    P_error_k_1 = (true_model.Phi_k - K_k_dash*true_model.H_k)*P_error_k* ...
        (true_model.Phi_k - K_k_dash*true_model.H_k)' + ...
        true_model.Gamma_k*Q_expectation*true_model.Gamma_k' + ...
        K_k_dash*R_expectation*K_k_dash';
end

